from main_backup import syllable_count

print(syllable_count('Bai Juyi lived during the Middle Tang period. This was a period of rebuilding and recovery for '
                     'the Tang Empire, following the An Lushan Rebellion, and following the poetically flourishing '
                     'era famous for Li Bai (701－762), Wang Wei (701－761), and Du Fu (712－770). Bai Juyi lived '
                     'through the reigns of eight or nine emperors, being born in the Dali regnal era (766-779) of '
                     'Emperor Daizong of Tang. He had a long and successful career both as a government official and '
                     'a poet, although these two facets of his career seemed to have come in conflict with each other '
                     'at certain points. Bai Juyi was also a devoted Chan Buddhist. Bai Juyi was born in 772 in '
                     'Taiyuan, Shanxi, which was then a few miles from location of the modern city, although he was '
                     'in Zhengyang, Henan for most of his childhood. His family was poor but scholarly, his father '
                     'being an Assistant Department Magistrate of the second-class. At the age of ten he was sent '
                     'away from his family to avoid a war that broke out in the north of China, and went to live with '
                     'relatives in the area known as Jiangnan, more specifically Xuzhou. Bai Juyi\'s official career '
                     'was initially successful. He passed the jinshi examinations in 800. Bai Juyi may have taken up '
                     'residence in the western capital city of Chang\'an, in 801. Not long after this, '
                     'Bai Juyi formed a long friendship with a scholar Yuan Zhen. Bai Juyi\'s father died in 804, '
                     'and the young Bai spent the traditional period of retirement mourning the death of his parent, '
                     'which he did along the Wei River, near to the capital. 806, the first full year of the reign of '
                     'Emperor Xianzong of Tang, was the year when Bai Juyi was appointed to a minor post as a '
                     'government official, at Zhouzhi, which was not far from Chang\'an (and also in Shaanxi '
                     'province). He was made a member (scholar) of the Hanlin Academy, in 807, and Reminder of the '
                     'Left from 807 until 815, except when in 811 his mother died, and he spent the traditional '
                     'three-year mourning period again along the Wei River, before returning to court in the winter '
                     'of 814, where he held the title of Assistant Secretary to the Prince\'s Tutor. It was not a '
                     'high-ranking position, but nevertheless one which he was soon to lose. While serving as a minor '
                     'palace official in 814, Bai managed to get himself in official trouble. He made enemies at '
                     'court and with certain individuals in other positions. It was partly his written works which '
                     'led him into trouble. He wrote two long memorials, translated by Arthur Waley as \"On Stopping '
                     'the War\", regarding what he considered to be an overly lengthy campaign against a minor group '
                     'of Tatars; and he wrote a series of poems, in which he satirized the actions of greedy '
                     'officials and highlighting the sufferings of the common folk. At this time, one of the post-An '
                     'Lushan warlords (jiedushi), Wu Yuanji in Henan, had seized control of Zhangyi Circuit (centered '
                     'in Zhumadian), an act for which he sought reconciliation with the imperial government, '
                     'trying to get an imperial pardon as a necessary prerequisite. Despite the intercession of '
                     'influential friends, Wu was denied, thus officially putting him in the position of rebellion. '
                     'Still seeking a pardon, Wu turned to assassination, blaming the Prime Minister, Wu Yuanheng, '
                     'and other officials: the imperial court generally began by dawn, requiring the ministers to '
                     'rise early in order to attend in a timely manner; and, on July 13, 815, before dawn, '
                     'the Tang Prime Minister Wu Yuanheng was set to go to the palace for a meeting with Emperor '
                     'Xianzong. As he left his house, arrows were fired at his retinue. His servants all fled, '
                     'and the assassins seized Wu Yuanheng and his horse, and then decapitated him, taking his head '
                     'with them. The assassins also attacked another official who favored the campaign against the '
                     'rebellious warlords, Pei Du, but was unable to kill him. The people at the capital were shocked '
                     'and there was turmoil, with officials refusing to leave their personal residences until after '
                     'dawn. In this context, Bai Juyi overstepped his minor position by memorializing the emperor. As '
                     'Assistant Secretary to the Prince\'s Tutor, Bai\'s memorial was a breach of protocol — he '
                     'should have waited for those of censorial authority to take the lead before offering his own '
                     'criticism. This was not the only charge which his opponents used against him. His mother had '
                     'died, apparently caused by falling into a well while looking at some flowers, and two poems '
                     'written by Bai Juyi — the titles of which Waley translates as \"In Praise of Flowers\" and '
                     '\"The New Well\" — were used against him as a sign of lack of Filial Piety, one of the '
                     'Confucian ideals. The result was exile. Bai Juyi was demoted to the rank of Sub-Prefect and '
                     'banished from the court and the capital city to Jiujiang, then known as Xun Yang, '
                     'on the southern shores of the Yangtze River in northwest Jiangxi Province. After three years, '
                     'he was sent as Governor of a remote place in Sichuan. At the time, the main travel route there '
                     'was up the Yangzi River. This trip allowed Bai Juyi a few days to visit his friend Yuan Zhen, '
                     'who was also in exile and with whom he explored the rock caves located at Yichang. Bai Juyi was '
                     'delighted by the flowers and trees for which his new location was noted. In 819, '
                     'he was recalled back to the capital, ending his exile.', convert='PYWG', skip_count=True,
                     error_skip=True, cherry_pick=True))
